pub mod asset;
pub mod entity;
pub mod job;
pub mod library;
pub mod selects;
pub mod system;

pub fn register_commands() -> impl Fn(tauri::ipc::Invoke<tauri::Wry>) -> bool + Send + Sync + 'static
{
    tauri::generate_handler![
        library::create_library,
        library::list_libraries,
        library::get_library,
        library::delete_library,
        library::start_scan,
        library::reconnect_library,
        asset::list_assets,
        asset::get_asset,
        asset::list_segments,
        asset::detect_asset_shots,
        asset::segment_preview_data_url,
        asset::add_segment_to_default_selects,
        asset::add_asset_acg_tag,
        asset::list_asset_acg_tags,
        asset::remove_asset_acg_tag,
        asset::search_assets,
        asset::find_similar_assets,
        asset::find_similar_by_reference_image,
        asset::recent_searches,
        asset::toggle_favorite,
        asset::favorite_asset_ids,
        asset::add_to_default_selects,
        asset::default_select_assets,
        asset::export_default_selects_csv,
        asset::export_default_selects_json,
        asset::export_default_selects_edl,
        asset::export_default_selects_fcpxml,
        job::list_jobs,
        job::pause_job,
        job::resume_job,
        job::cancel_job,
        job::retry_job,
        system::get_app_stats,
        system::acg_creator_pack_enabled,
        system::set_acg_creator_pack_enabled,
        system::semantic_model_status,
        system::install_semantic_model,
        system::reindex_semantic_assets,
        system::open_asset,
        system::reveal_asset_in_folder,
        system::copy_to_clipboard,
        entity::create_entity,
        entity::list_entities,
        entity::add_entity_reference_image,
        entity::list_entity_references,
        entity::remove_entity_reference,
        entity::set_entity_asset_feedback,
        entity::find_assets_for_entity,
        selects::list_select_collections,
        selects::create_select_collection,
        selects::list_select_items,
        selects::add_asset_to_select_collection,
        selects::update_select_item,
        selects::remove_select_item,
        selects::move_select_item,
        selects::reorder_select_item,
        selects::export_select_collection_csv,
        selects::export_select_collection_json,
        selects::export_select_collection_edl,
        selects::export_select_collection_fcpxml,
        selects::export_select_collection_contact_sheet,
    ]
}
